version: 2
registries:
  dockerhub:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_TOKEN }}
    replaces-base: true

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    assignees:
      - "Rakambda"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "-"
    groups:
      log4j:
        patterns:
          - "org.apache.logging.log4j:log4j-core"
          - "org.apache.logging.log4j:log4j-slf4j2-impl"
      google-apis:
        patterns:
          - "com.google.api-client:google-api-client"
          - "com.google.oauth-client:google-oauth-client-jetty"
          - "com.google.apis:google-api-services-gmail"
          - "com.google.apis:google-api-services-calendar"
#  Disable while paths can't be ignored as it'd update all 'auto-approve-sync-files.yml', Renovate will handle exclusion
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    assignees:
#      - "Rakambda"
#    schedule:
#      interval: "weekly"
#      time: "05:00"
#      timezone: "Europe/Paris"
#    pull-request-branch-name:
#      separator: "-"
  - package-ecosystem: "docker"
    directory: "/"
    assignees:
      - "Rakambda"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "-"
    registries:
      - dockerhub
  - package-ecosystem: "maven"
    directory: "/"
    assignees:
      - "Rakambda"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "-"
#  - package-ecosystem: "npm"
#    directory: "/"
#    assignees:
#      - "Rakambda"
#    schedule:
#      interval: "weekly"
#      time: "05:00"
#      timezone: "Europe/Paris"
#    pull-request-branch-name:
#      separator: "-"
  - package-ecosystem: "nuget"
    directory: "/"
    assignees:
      - "Rakambda"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "-"
    groups:
      restsharp:
        patterns:
          - "restsharp"
          - "restsharp.serializers.newtonsoftjson"
  - package-ecosystem: "pip"
    directory: "/"
    assignees:
      - "Rakambda"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Paris"
    pull-request-branch-name:
      separator: "-"
