name: Release

on:
  release:
    types: [ published ]

env:
  APP_JAVA_VERSION: 17

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE_FORGE_MODS }}" > keystoreForgeMods.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_FORGE_MODS_PASSPHRASE }}" --batch keystoreForgeMods.jks.asc > keystoreForgeMods.jks

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build mod file
        uses: gradle/gradle-build-action@v2.6.1
        with:
          cache-disabled: true
          arguments: |
            clean
            build
            -Dorg.gradle.project.version="${{ steps.get_release.outputs.name }}"
            -Dorg.gradle.project.changelog="[Changelog at ${{ steps.get_release.outputs.html_url }}](${{ steps.get_release.outputs.html_url }})\n\n${{ steps.get_release.outputs.body }}"
            -Dorg.gradle.project.forgeKeyStore="keystoreForgeMods.jks"
            -Dorg.gradle.project.forgeKeyStoreAlias="${{ secrets.KEYSTORE_FORGE_MODS_ALIAS }}"
            -Dorg.gradle.project.forgeKeyStorePass="${{ secrets.KEYSTORE_FORGE_MODS_STORE_PASS }}"
            -Dorg.gradle.project.forgeKeyStoreKeyPass="${{ secrets.KEYSTORE_FORGE_MODS_KEY_PASS }}"
            -Dorg.gradle.project.forgeSignSHA1="f927f4701bf4c0620c7bd0a501ce278f5e5ecc62"

      - name: Push on stores
        uses: gradle/gradle-build-action@v2.6.1
        with:
          cache-disabled: true
          arguments: |
            curseforge
            modrinth
            modrinthSyncBody
            -Dorg.gradle.project.version="${{ steps.get_release.outputs.name }}"
            -Dorg.gradle.project.changelog="[Changelog at ${{ steps.get_release.outputs.html_url }}](${{ steps.get_release.outputs.html_url }})\n\n${{ steps.get_release.outputs.body }}"
            -Dorg.gradle.project.curseforgeApiKey="${{ secrets.CURSEFORGE_API_KEY }}"
            -Dorg.gradle.project.modrinthToken="${{ secrets.MODRINTH_TOKEN }}"
            -Dorg.gradle.project.forgeKeyStore="keystoreForgeMods.jks"
            -Dorg.gradle.project.forgeKeyStoreAlias="${{ secrets.KEYSTORE_FORGE_MODS_ALIAS }}"
            -Dorg.gradle.project.forgeKeyStorePass="${{ secrets.KEYSTORE_FORGE_MODS_STORE_PASS }}"
            -Dorg.gradle.project.forgeKeyStoreKeyPass="${{ secrets.KEYSTORE_FORGE_MODS_KEY_PASS }}"
            -Dorg.gradle.project.forgeSignSHA1="f927f4701bf4c0620c7bd0a501ce278f5e5ecc62"

      - name: Push changes to the wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki/
