name: Release

on:
  release:
    types: [ published ]

env:
  APP_JAVA_VERSION: 17

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE_FORGE_MODS }}" > keystoreForgeMods.jks.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_FORGE_MODS_PASSPHRASE }}" --batch keystoreForgeMods.jks.asc > keystoreForgeMods.jks

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set gradle permissions
        run: chmod +x gradlew

      - name: Build mod file
        uses: gradle/gradle-build-action@v2.4.2
        env:
          ORG_GRADLE_PROJECT_version: "${{ steps.get_release.outputs.name }}"
          ORG_GRADLE_PROJECT_changelog: "[Changelog at ${{ steps.get_release.outputs.html_url }}](${{ steps.get_release.outputs.html_url }})\n\n${{ steps.get_release.outputs.body }}"
          ORG_GRADLE_PROJECT_forgeKeyStore: keystoreForgeMods.jks
          ORG_GRADLE_PROJECT_forgeKeyStoreAlias: ${{ secrets.KEYSTORE_FORGE_MODS_ALIAS }}
          ORG_GRADLE_PROJECT_forgeKeyStorePass: ${{ secrets.KEYSTORE_FORGE_MODS_STORE_PASS }}
          ORG_GRADLE_PROJECT_forgeKeyStoreKeyPass: ${{ secrets.KEYSTORE_FORGE_MODS_KEY_PASS }}
          ORG_GRADLE_PROJECT_forgeSignSHA1: f927f4701bf4c0620c7bd0a501ce278f5e5ecc62
        with:
          cache-disabled: true
          arguments: |
            clean
            build

      - name: Push on stores
        uses: gradle/gradle-build-action@v2.4.2
        env:
          ORG_GRADLE_PROJECT_version: "${{ steps.get_release.outputs.name }}"
          ORG_GRADLE_PROJECT_changelog: "[Changelog at ${{ steps.get_release.outputs.html_url }}](${{ steps.get_release.outputs.html_url }})\n\n${{ steps.get_release.outputs.body }}"
          ORG_GRADLE_PROJECT_curseforgeApiKey: ${{ secrets.CURSEFORGE_API_KEY }}
          ORG_GRADLE_PROJECT_modrinthToken: ${{ secrets.MODRINTH_TOKEN }}
          ORG_GRADLE_PROJECT_forgeKeyStore: keystoreForgeMods.jks
          ORG_GRADLE_PROJECT_forgeKeyStoreAlias: ${{ secrets.KEYSTORE_FORGE_MODS_ALIAS }}
          ORG_GRADLE_PROJECT_forgeKeyStorePass: ${{ secrets.KEYSTORE_FORGE_MODS_STORE_PASS }}
          ORG_GRADLE_PROJECT_forgeKeyStoreKeyPass: ${{ secrets.KEYSTORE_FORGE_MODS_KEY_PASS }}
          ORG_GRADLE_PROJECT_forgeSignSHA1: f927f4701bf4c0620c7bd0a501ce278f5e5ecc62
        with:
          cache-disabled: true
          arguments: |
            curseforge
            modrinth
            modrinthSyncBody

      - name: Push changes to the wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: actions@github.com
          GH_NAME: github-actions[bot]
